INSERT INTO MASTR 
SELECT 
    "Id",
    "AnlagenbetreiberId",
    "AnlagenbetreiberPersonenArt",
    "AnlagenbetreiberMaskedName",
    "AnlagenbetreiberMaStRNummer",
    "AnlagenbetreiberName",
    "BetriebsStatusId",
    "Breitengrad",
    "BundeslandId",
    CASE WHEN "DatumLetzteAktualisierung" IS NULL THEN NULL ELSE to_timestamp((substr("DatumLetzteAktualisierung", 7,LENGTH("DatumLetzteAktualisierung")-8)::bigint/1000)) END,
    CASE WHEN "EinheitMeldeDatum" IS NULL THEN NULL ELSE date(to_timestamp((substr("EinheitMeldeDatum", 7,LENGTH("EinheitMeldeDatum")-8)::bigint/1000))) END,
    "EinheitName",
    CASE WHEN "EndgueltigeStilllegungDatum" IS NULL THEN NULL ELSE date(to_timestamp((substr("EndgueltigeStilllegungDatum", 7,LENGTH("EndgueltigeStilllegungDatum")-8)::bigint/1000))) END,
    "Flurstueck",
    "Gemarkung",
    "Gemeinde",
    "Gemeindeschluessel",
    CASE WHEN "GeplantesInbetriebsnahmeDatum" IS NULL THEN NULL ELSE date(to_timestamp((substr("GeplantesInbetriebsnahmeDatum", 7,LENGTH("GeplantesInbetriebsnahmeDatum")-8)::bigint/1000))) END,
    "Hausnummer",
    CASE WHEN "InbetriebnahmeDatum" IS NULL THEN NULL ELSE date(to_timestamp((substr("InbetriebnahmeDatum", 7,LENGTH("InbetriebnahmeDatum")-8)::bigint/1000))) END,
    "IsNBPruefungAbgeschlossen",
    "Laengengrad",
    "LandId",
    "Landkreis",
    "LokationId",
    "LokationMastrNr",
    "MaStRNummer",
    "Migriert",
    "NetzbetreiberId",
    "NetzbetreiberMaskedNamen",
    "NetzbetreiberMaStRNummer",
    "NetzbetreiberNamen",
    "NetzbetreiberPersonenArt",
    "Ort",
    "Plz",
    "Strasse",
    "SystemStatusId",
    "Typ",
    "AktenzeichenGenehmigung",
    "AnzahlSolarModule",
    "Batterietechnologie",
    "Bruttoleistung",
    CASE WHEN "EegInbetriebnahmeDatum" IS NULL THEN NULL ELSE date(to_timestamp((substr("EegInbetriebnahmeDatum", 7,LENGTH("EegInbetriebnahmeDatum")-8)::bigint/1000))) END,
    "EegAnlageMastrNummer",
    CASE WHEN "EegAnlageMeldedatum" IS NULL THEN NULL ELSE date(to_timestamp((substr("EegAnlageMeldedatum", 7,LENGTH("EegAnlageMeldedatum")-8)::bigint/1000))) END,
    "EegAnlagenschluessel",
    "EegZuschlag",
    "EnergietraegerId",
    "EnergietraegerName",
    "GemeinsamerWechselrichter",
    "Genehmigungbehoerde",
    CASE WHEN "GenehmigungDatum" IS NULL THEN NULL ELSE date(to_timestamp((substr("GenehmigungDatum", 7,LENGTH("GenehmigungDatum")-8)::bigint/1000)))  END,
    CASE WHEN "GenehmigungMeldedatum" IS NULL THEN NULL ELSE date(to_timestamp((substr("GenehmigungMeldedatum", 7,LENGTH("GenehmigungMeldedatum")-8)::bigint/1000)))  END,
    "GenehmigungsMastrNummer",
    "Gruppierungsobjekte",
    "GruppierungsobjekteIds",
    "HatFlexibilitaetspraemie",
    "HauptausrichtungSolarModule",
    "HauptbrennstoffId",
    "HauptneigungswinkelSolarmodule",
    "HerstellerWindenergieanlage",
    "HerstellerWindenergieanlageBezeichnung",
    "IsAnonymisiert",
    "IsEinheitNotstromaggregat",
    "KraftwerkName",
    "KraftwerkBlockName",
    "KwkAnlageElektrischeLeistung",
    CASE WHEN "KwkAnlageInbetriebnahmedatum" IS NULL THEN NULL ELSE date(to_timestamp((substr("KwkAnlageInbetriebnahmedatum", 7,LENGTH("KwkAnlageInbetriebnahmedatum")-8)::bigint/1000))) END,
    "KwkAnlageMastrNummer",
    CASE WHEN "KwkAnlageMeldedatum" IS NULL THEN NULL ELSE date(to_timestamp((substr("KwkAnlageMeldedatum", 7,LENGTH("KwkAnlageMeldedatum")-8)::bigint/1000))) END,
    "KwkZuschlag",
    "LageEinheit",
    "LageEinheitBezeichnung",
    "Leistungsbegrenzung",
    "MieterstromAngemeldet",
    "MigrationseinheitMastrNummer",
    "NabenhoeheWindenergieanlage",
    "Nettonennleistung",
    "NutzbareSpeicherkapazitaet",
    "NutzungsbereichGebSA",
    "Pilotwindanlage",
    "Prototypanlage",
    "Regelzone",
    "RotordurchmesserWindenergieanlage",
    "SpannungsebenenId",
    "SpannungsebenenNamen",
    "SpeicherEinheitMastrNummer",
    "Statistik",
    "TechnologieStromerzeugungId",
    "ThermischeNutzleistung",
    "Typenbezeichnung",
    "VollTeilEinspeisung",
    "WasserkraftErtuechtigung",
    "WindClusterOstseeId",
    "WindClusterNordseeId",
    "WindparkName"
FROM mastr_stage
;
